# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='user_url',
            field=models.URLField(max_length=4000),
        ),
    ]
